### ISSUE TITLE
Directory entries aren't expanded when passed to a shell?

### ISSUE THREAD

**Issue by vonHabsi** [plexus/chemacs2#46]
The entry for a DOOMDIR in my `~/.emacs-profiles.el` is  `DOOMDIR` is `("DOOMDIR" . "~/Data/Emacs/doom_dirs/01.doom.01")`.

I notice that when I start a terminal eg `vterm` it is passed as a quoted string so `ls $DOOMDIR` results in a directory not found error.

In the shell  setting `DOOMDIR=~/Data/Emacs/doom_dirs/01.doom.01` results in `ls $DOOMDIR` giving the expected result but `DOOMDIR="~/Data/Emacs/doom_dirs/01.doom.01"` or `DOOMDIR='~/Data/Emacs/doom_dirs/01.doom.01'` i.e. quoting the value means it is not expanded, and so `ls` takes the literal quoted string.

I don't know where the fault is but it seems there should be away of passing the values to the shell in the expected manner. Chemacs2 is clearly passing on the value as entered in `~/.emacs-profiles.el`.

Is this likely to be an Emacs thing and is there some workaround for this?

**Comment by plexus** [comment]
`~` is something that your shell would expand, similar to `*`, or referencing other vars like `$HOME`.

Chemacs on the other hand simply sets the env var to the value you give it, we don't expand it in any way. We can't, because we don't know what is a filename and what isn't. You might have something else in an env var that contains `~`, and where it should not be expanded to your home directory.

You can try putting something like this in your emacs startup code

```emacs-lisp
(setenv "DOOMDIR" (expand-file-name (getenv "DOOMDIR")))
```
